FROM ubuntu:20.04

# valgrind: ulimit -n 1024
RUN apt-get update && apt-get install -y git gcc make uuid-dev vim bash curl libpcre3-dev socat
RUN DEBIAN_FRONTEND=noninteractive apt-get -yq install bsd-mailx

RUN sh -c "`curl -L https://raw.githubusercontent.com/rylnd/shpec/master/install.sh`"

WORKDIR /usr/app
COPY . .
