FROM ubuntu:20.04

RUN apt-get update && apt-get install -y git gcc make uuid-dev vim

# RUN sh -c "`curl -L https://raw.githubusercontent.com/rylnd/shpec/master/install.sh`"

WORKDIR /usr/app
COPY . .

# docker build -f Dockerfile.dev -t chronic .
# docker run -it --entrypoint /bin/bash -v `pwd`:/usr/app chronic
# mkdir -p /var/spool/cron/crontabs
# mkdir -p /home/cookie && useradd cookie
# touch /var/spool/cron/crontabs/cookie
# chmod 600 /var/spool/cron/crontabs/cookie
# echo '*/1 * * * * /usr/app/t/fixtures/script.sh min' > /var/spool/cron/crontabs/cookie
