CC          ?= gcc
AR          ?= ar
FMT         ?= clang-format
INSTALL     := install

INSTALL_DIR ?= /usr/local
MAN_DIR     ?= /usr/share/man/man1

PROG        := chronic
PROGVERS    := 0.0.1
MANPAGE     := $(PROG).1
